---
title: "Holdings"
author: "Joseph Bennett"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
bs.bmrn <- matrix(c(2956,6842,1177,1087,1890,4952,6842,2751,6375,589,1085,1772,4603,6375,2274,6003,540,1083,1733,4271,6003, 2342,5848,493,1082,1742,4106,5848,1942,4690,933,858,1568,3122,4690),ncol=5)
row.names(bs.bmrn) <- c("Total Current Assets", "Total Assets", "Total Current Liabilities", "Total Debt", "Total Liabilities", "Total Equity", "Total Liabilities & Shareholders' Equity")
colnames(bs.bmrn) <- c("2023","2022","2021","2020","2019")
is.bmrn <- matrix(c(2419, 2286, 134, 189, 168, 168, 0, 168, 168, 168, 0, 213, 189, 189, 2096, 1946, 150, 150, 123, 123, 18.75, 142, 123, 142, 0, 65, 53, 53, 1846, 1929, -82, -75, -68, -68, 3.92, -64, -68, -64, 0, -75, -68, -68, 1860, 1897, -37, -42, 4.56, 4.56, 855, 859, 4.59, 859, 0, -102, 34, 34, 1704, 1805, -100, -95, -24 -24, 0, -24, -24, -24, 0, -120, -40, -40), ncol=5)
row.names(is.bmrn) <- c("Total Revenue", "Total Operating Expense",
                        "Total Operating Income",
                        "Income Before Tax", "Net Income After Taxes",
                        "Net Income Before Extra Items",
                        "Total Extraordinary Items", "Net Income",
                        "Income Available to Common Excl. Extra. Items",
                        "Income Available to Common Incl. Extra. Items",
                        "Pro Forma Net Income", "Normalized Income Before Tax",
                        "Normalized Income After Tax",
                        "Normalized Income Avail To Common")
colnames(is.bmrn) <- c("2023", "2022", "2021", "2020", "2019")
is.bmrn.working <- is.bmrn[c(1:4,8),]
is.bmrn
```

```{r}
(pct.change.revenue <- (2419 - 2096) / 2096)
(chg.revenue <- 2419-2096)
(chg.current.liabilities <- 1177 - 589)
(pct.change.liabilities <- (1177 - 589) / 589)
```