---
title: "Financial Statements and Cash Flow for US Composite Corp."
author: "Ross"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: 
  pdf_document:
   toc: true 
---

# Balance Sheet

```{r balance sheet data, echo=F}
current.assets.2011 <- c(
  # Cash and equivalents
  140,
  # Accounts receivable
  294,
  # Inventory
  269,
  # Other
  58
)
current.assets.2012 <- c(
  # Cash and equivalents
  107,
  # Accounts receivable
  270,
  # Inventory
  280,
  # Other
  50
)
fixed.assets.2011 <- c(
  # Property,plant, and equipment
  1423,
  # Less accumulated deprecation
  -550
)
fixed.assets.2012 <- c(
  # Property,plant, and equipment
  1274,
  # Less accumulated deprecation
  -460
)
intangible.assets.and.others.2011 <- 245
intangible.assets.and.others.2012 <- 221
current.liabilities.2011 <- c(
  # Accounts payable
  213,
  # Notes payable
  50,
  # Accrued expenses
  223
)
current.liabilities.2012 <- c(
  # Accounts payable
  197,
  # Notes payable
  53,
  # Accrued expenses
  205
)
long.term.liabilities.2011 <- c(
  # Deferred taxes
  117,
  # Long-term debt
  471
)
long.term.liabilities.2012 <- c(
  # Deferred taxes
  104,
  # Long-term debt
  458
)
stockholders.equity.2011 <- c(
  # Preferred stock
  39,
  # Common stock ($1 par value)
  55,
  # Capital surplus
  347,
  # Accumulated retained earnings
  390,
  # Less treasury stock
  26
)
stockholders.equity.2012 <- c(
  # Preferred stock
  39,
  # Common stock ($1 par value)
  32,
  # Capital surplus
  327,
  # Accumulated retained earnings
  347,
  # Less treasury stock
  20
)
```

```{r balance sheet build, echo=F}
bs.current.assets <- matrix(c(current.assets.2011, sum(current.assets.2011),
                              current.assets.2012, sum(current.assets.2012)),
                            ncol=2)
rownames(bs.current.assets) <- c("Cash and equivalents", "Accounts receivable",
                                 "Inventory", "Other", "Total current assets")
colnames(bs.current.assets) <- c("2011", "2012")
bs.fixed.assets <- matrix(c(fixed.assets.2011,
                            sum(fixed.assets.2011),
                            intangible.assets.and.others.2011,
                            sum(c(fixed.assets.2011, intangible.assets.and.others.2011)),
                            fixed.assets.2012, sum(fixed.assets.2012),
                            intangible.assets.and.others.2012,
                            sum(c(fixed.assets.2012, intangible.assets.and.others.2012))),
                          ncol=2)
rownames(bs.fixed.assets) <- c("Property, plant, and equipment",
                               "Less accumulated deprecation",
                               "Net property, plant, and equipment",
                               "Intangible assets and others",
                               "Total fixed assets")
colnames(bs.fixed.assets) <- c("2011", "2012")
bs.assets <- list("Current assets" = bs.current.assets,
                  "Fixed assets" = bs.fixed.assets)

bs.current.liabilities <- matrix(c(current.liabilities.2011, sum(current.liabilities.2011),
                                   current.liabilities.2012, sum(current.liabilities.2012)),
                                 ncol=2)
rownames(bs.current.liabilities) <- c("Accounts payable", "Notes payable",
                                      "Accrued expenses", "Total current liabilities")
colnames(bs.current.liabilities) <- c("2011", "2012")
bs.long.term.liabilities <- matrix(c(long.term.liabilities.2011, sum(long.term.liabilities.2011),
                                     long.term.liabilities.2012, sum(long.term.liabilities.2012)),
                                   ncol=2)
rownames(bs.long.term.liabilities) <- c("Deferred taxes", "Long-term debt", "Total long-term liabilities")
colnames(bs.long.term.liabilities) <- c("2011", "2012")
bs.liabilities <- list("Current liabilities" = bs.current.liabilities,
                       "Long-term liabilities" = bs.long.term.liabilities)
bs.stockholders.equity <- matrix(c(stockholders.equity.2011,
                                   sum(stockholders.equity.2011),
                                   stockholders.equity.2012,
                                   sum(stockholders.equity.2012)),
                                 ncol=2)
rownames(bs.stockholders.equity) <- c("Preferred stock", "Common stock ($1 par value)",
                                      "Capital surplus", "Accumulated retained earnings",
                                      "Less treasury stock", "Total equity")
colnames(bs.stockholders.equity) <- c("2011", "2012")
us.composite.corporation.balance.sheet <- list(bs.current.assets,
                                               bs.fixed.assets,
                                               bs.current.liabilities,
                                               bs.long.term.liabilities,
                                               bs.stockholders.equity)
knitr::kable(us.composite.corporation.balance.sheet)
```











