---
title: Chapter 25 Derivatives and Hedging Risk
subtitle: Text
output:
  pdf_document:
    toc: true
    includes:
      in_headers: preamble.tex
---

# 25.1 Derivatives, Hedging, and Risk

A derivative is a firnancial instrument whose payoffs and values are derived
from, or depend on, something else. The _thing_ the derivative depends on is
called the _primitive_ or the _underlying_.

An option is a derivative. The value of a calloption depends on the value of the
underlying stock on which it is written.

Derivatives are tools that firm's use to change its risk exposure. Firm's can
use derivatives to mitigate risks. When a firm reduces its risk exposure with
the use of derivatives, it is said to be hedging.

Derivatives can also be used to enhance risk exposure and benefit from economic
changes. This is called speculating.

# 25.2 Forward Contracts

A Forward contract is a simple derivative. Forward contracts are used by firms
to lock in the price of something in the future. One firm would _write_ the
contract and agree to sell the item to the other firm at a set date and at a set
price. The item that is to be transferred is called the delivarable instrument,
and the act of transferring the item is called making a delivery. The price,
date, and other conditions are set in the contract.

# 25.3 Futures Contracts

Futures contracts are similar to forward contracts except they are transferrable
and are traded on exchanges. There are a number of exchanges that trade futures
contracts such as the CME Group's CME (Chicago Mercantile Exchange) and CBT
(Chicago Board of Trade) platforms. Other notable exchanges include the London
International Financial Futures and Options Exchange (LIFFE). The New York
Mercantile Exchange (NYM) is also now owned by the CME Group.

The differences between futures and forward contracts:

1. The seller can choose to deliver the underlying item on any day during the
   delivery month. This gives the seller leeway that he would not have with a
   forward contract. When the seller decides to deliver he notifies the exchange
   clearinghouse that he wants to do so. The  clearinghouse then notifies an
   individual who bought the contract to stand ready to accept delivery within
   the next few days.

2. Futures contracts are traded on an exchange, whereas forward contracts are
   traded off an exchange.

3. The prices of futures contracts are marked to the market daily. This means
   that the buyers and sellers need to reconcile price differences with the
   exchange each day.

The mark-to-the-market provision on futures contracts has two related effects.
The first concerns differnces in net present value. For example, a large price
drop immediately following the purchase means an immediate outpayment for the
buyer of a futures contract.

The second effect is that the firm must have extra liquidity to handle a sudden
outflow prior to expiration.

The purpose of mark-to-the-market feature of exchanges is to ensure that traders
do not default on their positions.

# 25.4 Hedging

#### Example 25.1 Futures Hedging

In June, Bernard Abelman, a Midwestern farmer, anticipates a harvest of 50,000
bushels of wheat at the end of September. He has two alternatives:

1. _Write futures contracts against his anticipated harvest._ The September
   wheat contract on the Chicago Board of Trade is trading at \$3.75 a bushel on
   June 1. He executes the trade of writing 10 September futures contracts at
   the price of \$3.75 on June 1. He notes that transportation costs to the
   designated delivery point in Chicago are 30 cents/bushel. Thus, his net price
   per bushel is \$3.45 = \$3.75 - \$.30.

2. _Harvest the wheat without writing a futures contract._ Alternatively, Mr.
   Abelman could harvest the wheat without the benefit of a futures contract.
   The risk would be quite great here because no one knows what the cash price
   in September will be. If prices rise, he will profit. Conversely, he will
   lose if prices fall.

We say that Strategy 2 is an unhedged position because there is no attempt to use
the futures markets to reduce risk. Conversely, Strategy 1 involves a hedge.
That is, a position in the futures market offsets the risk of a position in the
physical--that is, in the actual--commodity.

Though hedging may seem quite sensible to you, it should be mentioned that not
everyone hedges. Mr. Abelman might reject hedging for at least two reasons.

First, he may simply be uninformed about hedging. We have found that not
everyone in business understands the hedging concept. Many executives have told
us that they do not want to use futures markets for hedging their inventories
because the risks are too great. However, we disagree. While there are large
price fluctuations in these markets, hedging actually reduces the risk that an
individual holding inventories bears.

Second, Mr. Abelman may have a special insight or some special information that
commodity prices will rise. He would not be wise to lock in a price of \$3.75 if
he expects the cash price in September to be well above this price.

The hedge of Strategy 1 is called a short hedge because Mr. Abelman reduces his
risk by _selling_ a futures contract. The short hedge is very common in
business. It occurs whenever someone either anticipates receiving inventory or
is holding inventory. Mr. Abelman is anticipating the harvest of grain. A
manufacturer of soybean meal and oil may hold large quantities of raw soybeans
that are already paid for. However, the prices to be received for meal and oil
are not known because no one knwos what the market prices will be when the meal
and oil are produced. The manufacturer may write futures contracts in meal and
oil to lock in sales prices. An oil company may hold large inventories of
petroleum to be processed into heating oil. The firm could sell futures
contracts in heading oil to lock in the sales price. A mortgage banker may
assemble mortgages slowly before selling them in bulk to a financial
institution. Movements of interest rates affect the value of the mortgages while
they are in inventory. The mortgage banker could sell Treasury bond futures
contracts to offset this interest rate risk.


#### Example 25.2 More Hedging

On April 1, Moon Chemical agreed to sell petrochemicals to the U.S. government
in the future. The delivery dates and prices have been determined. Because oil
is a basic ingredient in the production process, Moon Chemical will need to have
large quantities of oil on hand. The firm can get the oil in one of two ways:

1. _Buy the oil as the firm needs it._ This is an unhedged position because, as
   of April 1, the firm does not know the prices it will later have to pay for
   the oil. Oil is quite a volatile commodity, so Moon Chemical is bearing a
   good bit of risk. The key to this risk bearing is that the sales price to the
   U.S. government has already been fixed. Thus, Moon Chemical cannot pass on
   increased costs to the consumer.

2. _Buy futures contracts._ The firm can buy futures contracts with expiration
   months corresponding to the dates the firm needs inventory. The futures
   contracts lock in the purchase price to Moon Chemical. Because there is a
   crude oil futures contract for every month, selecting the correct futures
   contract is not difficult. Many other commodities have only five contracts
   per year, frequently necessitating buying contracts one month away from the
   month of production.

   As mentioned earlier, Moon Chemical is interested in hedging the risk of
   fluctuating oil prices because it cannot pass any cost increases on to the
   consumer. Suppose, alternatively, that Moon Chemical was not selling
   petrochemicals on a fixed contract to the U.S. government. Instead, imagine
   that the petrochemicals were to be sold to private industry at currently
   prevailing prices. The price of petrochemicals should move directly with oil
   prices because oil is a major component of petrochemicals. Because cost
   increases are likely to be passed on to the consumer, Moon Chemical would
   probably not want to hedge in this case. Instead, imagine that the
   petrochemicals were to be sold to private industry at currently prevailing
   prices. The price of petrochemicals should move directly with oil prices
   because oil is a major component of petrochemicals. Because cost increases
   are likely to be passed on to the consumer, Moon Chemical would probably not
   want to hedge in this case. Instead, the firm is likely to choose Strategy 1,
   buying the oil as it is needed. If oil prices increase between April 1 and,
   say, September 1, Moon Chemical will, of course, find that its inputs have
   become quite costly. However, in a competitive market, its revenues are
   likely to rise as well.

   Strategy 2 is called a __long hedge__ because one purchases a futures
   contract to reduce risk. In other words, one takes a long position in the
   futures market. In general, a firm institutes a long hedge when it is
   committed to a fixed sales price. One class of situations involves actual
   written contracts with customers, such as the one Moon Chemical had with the
   U.S. government. Alternatively, a firm may find that it cannot easily pass on
   costs to consumers or does not want to pass on these costs. For example, a
   group of students opened a small meat market called _What's Your Beef_ near
   the University of Pennsylvania in the late 1970s. This was a time of volatile
   consumer prices, especially food prices. Knowing that their fellow students
   were particularly budget-conscious, the owners vowed to keep food prices
   constant regardless of price movements in either direction. They accomplished
   this by purchasing futures contracts in various agricultural commodities.

# 25.5 Interest Rate Futures contracts

## Pricing of Treasury bonds

Imagine a 20-year 8 percent semi-annual coupon treasury bonds that are issued
March 1. There are 40 (two a year) payments plus the principal paid at maturity.

\begin{equation}
P_{\text{TB}} = \frac{\$40}{1 + R_1} + \frac{\$40}{(1 + R_2)^2}
  + \frac{\$40}{(1 + R_3)^3} + \cdots + \frac{\$40}{(1 + R_{39})^{39}}
  + \frac{\$40}{(1 + R_{40})^{40}}\tag{25.1}\label{eq:25.1}
\end{equation}

The proper way to price the bond is to discount each semi-annual payment by the
appropriate spot rate. If the effective annual yield is 8 percent for all
maturities then each spot rate would be \(\sqrt{1.08} - 1 = 3.92\%\).

## Pricing Forward Contracts

Now imagine thay you are buying a _forward_ contract where, on March 1, you
agree to buy a new 20-year, 8 percent coupon Treasury bond in six months
(September 1). You will pay for the bond on September 1. When contrasting this
with the straight purchase of the Treasury bond, the cash flows for the Treasury
bond begin on September 1 (we state Date 1). This is six months earlier then the
forward contract on March 1 (Date 2). For the Treasury bond, the last coupon
payment with principal is paid at the end of the 20-year maturity (Date 40). For
the forward contract, the last coupon and principal payment is paid out at Date
41.

The forward contract compels you to pay \(P_{\text{FORWARD.CONT}}\}\), the price
of the forward contract, on September 1 (Date 1). Whereas you pay the face value
(\$1,000) for the Treasury bond on March 1 (Date 0). The equation for the
forward contract can be stated:

\begin{equation}
\frac{P_{\text{FORWARD.CONT}}}{1 + R_1} = \frac{\$40}{(1 + R_2)^2}
  + \frac{\$40}{(1 + R_3)^3} + \frac{\$40}{(1 + R_4)^4} + \cdots
  + \frac{\$40}{(1 + R_{40})^{40}} + \frac{\$40}{(1 + R_{41})^{41}}
  \tag{25.2}\label{eq:25.2}
\end{equation}

The actual payment for the Treasury bond in the futures contract occurs on Date
1, so we must discount this back to date 0 (Hence dividing by \((1 + R_1)\)).
We can rewrite the equation to solve for \(P_{\text{FORWARD.CONT}}\):

\begin{equation}
P_{\text{FORWARD.CONT}} =
    \frac{\$40 \times (1 + R_1)}{(1 + R_2)^2}
  + \frac{\$40 \times (1 + R_1)}{(1 + R_3)^3}
  + \frac{\$40 \times (1 + R_1)}{(1 + R_4)^4}
  + \cdot
  + \frac{\$40 \times (1 + R_1)}{(1 + R_{40})^{40}}
  + \frac{\$40 \times (1 + R_1)}{(1 + R_{41})^{41}}
\tag{25.3}\label{eq:25.3}
\end{equation}

## Futures contracts

Futures and forward contracts are very similar. There are some differences:

1. Futures contracts are traded on exchanges. Forward contracts are between two
   parties.

2. Futures contracts give the seller a period of time in which to deliver the
   bond (usually within the month of the contract maturity). Forward contracts
   have the specific date specified.

3. Futures contracts are subject to mark-to-market conventions.

## Hedging in interest rate futures

#### Example 25.3 Interest Rate Hedging

Ron Cooke owns a mortgage banking company. On March 1, he made a commitment to
lend a total of \$1 million to various homeowners on May 1. The loans are
20-year mortgages carrying a 12 percent coupon, the going interest rate on
mortgages at the time. Thus, the mortgages are made at par. Though homeowners
would not use the term, we could say that he is buying a _forward contract_ on a
martgage. That is, he agrees on March 1 to give \$1 million to his borrowers on
May 1 in exchange for principal and interest from them every month for the next
20 years.

Like many mortgage bankers, he has no intention of paying the \$1 million out of
his own pocket. Rather, he intends to sell the mortgages to an insurance
company. Thus, the insurance company will actually lend the funds and will
receive principal and interest over the next 20 years. Mr. Cooke does not
currently have an insurance company in mind. He plans to visit the mortgage
departments of insurance companies over the next 60 days to sell the mortgages
to one or many of them. He sets April 30 as a deadline for making the sale
because the borrowers expect the funds on the following day.

Suppose Mr. Cooke sells the mortgages to the Acme Insurance Co. on April 15.
What price will Acme pay for the bonds?

You may think the insurance company will obviously pay \$1 million for the
loans. However, suppose interest rates have risen above 12 percent by April 15.
The insurance company will buy the mortgage at a discount. For example, suppose
the insurance company agrees to pay only \$940,000 for the mortgages. Because
the mortgage banke agreed to lend a full \$1 million to the borrowers, the
mortgage banker must come up with the additional \$60,000 (=\$1 million -
\$940,000) out of his own pocket.

Alternatively, suppose interest rates fall below 12 percent by April 15. The
mortgages can be sold at a premium under this scenario. If the insurance company
buys the mortgages at \$1.05 million, the mortgage banker will have made an
unexpected profit of \$50,000 (=\$1.05 million - \$1 million).

Becuase Ron Cooke is unable to forecast interest rates, this risk is something
that he would like to avoid.
